//
//  HeaderField.swift
//  SimpleWebservice
//
//  Created by cleanmac-ada on 18/12/22.
//

import Foundation

public enum HeaderField: String {
    
    case aim = "A-IM"
    case accept = "Accept"
    case acceptCharset = "Accept-Charset"
    case acceptDatetime = "Accept-Datetime"
    case acceptEncoding = "Accept-Encoding"
    case acceptLanguage = "Accept-Language"
    case accessControlRequestMethod = "Access-Control-Request-Method"
    case accessControlRequestHeaders = "Access-Control-Request-Headers"
    case authorization = "Authorization"
    case cacheControl = "Cache-Control"
    case connection = "Connection"
    case contentEncoding = "Content-Encoding"
    case contentLength = "Content-Length"
    case contentMd5 = "Content-MD5"
    case contentType = "Content-Type"
    case cookie = "Cookie"
    case date = "Date"
    case expect = "Expect"
    case forwarded = "Forwarded"
    case from = "From"
    case host = "Host"
    case http2Settings = "HTTP2-Settings"
    case ifMatch = "If-Match"
    case ifModifiedSince = "If-Modified-Since"
    case ifNoneMatch = "If-None-Match"
    case ifRange = "If-Range"
    case ifUnmodifiedSince = "If-Unmodified-Since"
    case maxForwards = "Max-Forwards"
    case origin = "Origin"
    case pragma = "Pragma"
    case prefer = "Prefer"
    case proxyAuthorization = "Proxy-Authorization"
    case range = "Range"
    case referer = "Referer"
    case te = "TE"
    case trailer = "Trailer"
    case transferEncoding = "Transfer-Encoding"
    case userAgent = "User-Agent"
    case upgrade = "Upgrade"
    case via = "Via"
    case warning = "Warning"
    
    case upgradeInsecureRequest = "Upgrade-Insecure-Request"
    case xRequestedWith = "X-Requested-With"
    case dnt = "DNT"
    case xForwardedFor = "X-Forwarded-For"
    case xForwardedHost = "X-Forwarded-Host"
    case xForwardedProto = "X-Forwarded-Proto"
    case frontEndHttps = "Front-End-Https"
    case xHttpMethodOverride = "X-HTTP-Method-Override"
    case xAttDeviceid = "X-Att-Deviceid"
    case xWapProfile = "x-wap-profile"
    case proxyConnection = "Proxy-Connection"
    case xUidh = "X-UIDH"
    case xCsrfToken = "X-Csrf-Token"
    case xRequestId = "X-Request-ID"
    case xCorrelationId = "X-Correlation-ID"
    case saveData = "Save-Data"
    
    case acceptCh = "Accept-CH"
    case accessControlAllowOrigin = "Access-Control-Allow-Origin"
    case accessControlAllowCredentials = "Access-Control-Allow-Credentials"
    case accessControlExposeHeaders = "Access-Control-Expose-Headers"
    case accessControlMaxAge = "Access-Control-Max-Age"
    case accessControlAllowMethods = "Access-Control-Allow-Methods"
    case accessControlAllowHeaders = "Access-Control-Allow-Headers"
    case acceptPatch = "Accept-Patch"
    case acceptRanges = "Accept-Ranges"
    case age = "Age"
    case allow = "Allow"
    case altSvc = "Alt-Svc"
    
}
